<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD 추가 -->

<!DOCTYPE memberList
[
<!ELEMENT memberList (memberInfo+)>
<!ELEMENT memberInfo (name, tel, addr)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT addr (#PCDATA)>
<!ATTLIST memberInfo mid CDATA #IMPLIED>
]>

<!-- 여러 개면 + 붙이기 -->
<!-- 있을 수도 있고 없을 수도 있으면 ? 붙이기 -->
<!-- #REQUIRED : 이 속성은 반드시 명시되어야 한다. -->
<!-- #IMPLIED : 이 속성은 명시되기도 하고, 명시되지 않기도 한다. -->
<!-- #FIXED 특정값 : 이 속성은 특정값으로 고정되어 사용된다. -->

<memberList>

	<memberInfo mid="1">
		<name>최문정</name>
		<tel><![CDATA[010-2877-0992]]></tel>
		<addr>인천시 연수구</addr>
	</memberInfo>
	
	<memberInfo mid="2">
		<name>홍은혜</name>
		<tel><![CDATA[010-2877-0992]]></tel>
		<addr>경기도 용인시</addr>
	</memberInfo>
	
</memberList>

